#!/bin/bash
#
# Ars Magica Grimoire - bash script
#
# Flavio Serreri (2018)
#

# base script install dir
INSTALLDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

# path di installazione utility: SAXON e FOP

# c:\winutil\saxon\saxon9he.jar
SAXON_PATH="${INSTALLDIR}/processors/Saxon/saxon9he.jar"
# c:\WinUtil\fop\fop
FOP_PATH="${INSTALLDIR}/processors/fop"

# verifica la presenza dei processori, altrimenti tenta di ricavarla
# estraendola dall'archivio

if [ ! -f ${INSTALLDIR}/processors/.gitignore ]; then
  tar xzf ${INSTALLDIR}/processors/processors.tar.gz -C ${INSTALLDIR}/processors
fi

# parametri di configurazione
template=spellbook.xsl
print=
flow=
source=ars_spells.xml
cover=true
spellsource=true
paper=letter
orientation=portrait

while getopts ":cfs:Ppo" opt; do
  case $opt in
    c)
      cover=false;
      ;;
    f)
      flow=true;
      ;;
    s)
      source=$OPTARG;
      ;;
    P)
      print=true;
      ;;
    p)
      paper=$OPTARG:
      ;;
    o)
      orientation=$OPTARG;
      ;;
    \?)
      echo "Opzione invalida: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG richiede un argomento" >&2
      exit 1
      ;;
  esac
done

# riceve da pipeline. I parametri di commandline non vengono utilizzati.

java -cp ${SAXON_PATH} net.sf.saxon.Transform -t -s:- -xsl:"${template}" \
      edit=$print cover=$cover flow=$flow paper=$paper orientation=$orientation source=$spellsource \
      | ${FOP_PATH}/fop -fo - -pdf - -c ${INSTALLDIR}/fop.cfg

